"""Traducción al inglés de los textos de las ilustraciones (clave: el texto en español tal como aparece en fig_*.py).

Los textos que no dependen del idioma (números, fórmulas, símbolos, nombres de moléculas) están en ``_NEUTROS``
y se traducen a sí mismos; así ``lienzo.faltan`` solo lista lo que de verdad falta.
"""

FIG_EN: dict[str, str] = {
    # ------------------------------------------------------------------ pastillas (etiquetas de tipo)
    "Analogía": "Analogy",
    "La ecuación, término a término": "The equation, term by term",
    "La ecuación, en palabras": "The equation, in words",
    "Cómo se mide": "How it is measured",
    "Resumen": "Summary",
    "El curso en una imagen": "The course in one picture",
    "La reacción": "The reaction",
    "Por qué importa": "Why it matters",
    "Para pensar": "Think about it",
    "Modelo": "Model",
    "Datos reales": "Real data",
}

FIG_EN.update({
    # ------------------------------------------------------------------ fig_06: colina / Eyring
    "Una reacción es una pelota que intenta cruzar una colina": "A reaction is a ball trying to get over a hill",
    "Rebota miles de millones de veces por segundo; solo muy pocos intentos llegan a la cima":
        "It bounces billions of times per second; only a very few attempts reach the summit",
    "estado de transición": "transition state",
    "(la cima de la colina)": "(the top of the hill)",
    "altura de": "height of",
    "la colina": "the hill",
    "reactivos": "reactants",
    "glucosa + ATP": "glucose + ATP",
    "productos": "products",
    "intento fallido: vuelve al valle": "failed attempt: rolls back to the valley",
    "intento con éxito: cruza la cima": "successful attempt: crosses the summit",
    "Eyring en palabras: velocidad = intentos × probabilidad de éxito": "Eyring in words: rate = attempts × probability of success",
    "intentos por segundo": "attempts per second",
    "la molécula «choca» contra": "the molecule “runs into”",
    "la colina ~6 × 10^{12} veces/s": "the hill ~6 × 10^{12} times/s",
    "probabilidad de llegar arriba": "probability of reaching the top",
    "fracción de intentos con": "fraction of attempts with",
    "energía suficiente (muy pequeña)": "enough energy (very small)",
    "Regla de oro": "Rule of thumb",
    "cada 1.36 kcal/mol más": "every extra 1.36 kcal/mol",
    "de colina ⇒ 10 veces": "of hill ⇒ 10 times",
    "más lenta": "slower",
    "más barrera →": "higher barrier →",

    # ------------------------------------------------------------------ fig_A: inicio
    "El ensayo acoplado: convertir G6P en luz absorbida": "The coupled assay: turning G6P into absorbed light",
    "Una segunda enzima produce NADPH, que absorbe luz ultravioleta de 340 nm":
        "A second enzyme makes NADPH, which absorbs 340 nm ultraviolet light",
    "6-fosfoglucono-": "6-phosphoglucono-",
    "δ-lactona": "δ-lactone",
    "glucoquinasa": "glucokinase",
    "(la que medimos)": "(the one we measure)",
    "(en exceso)": "(in excess)",
    "contar NADPH es contar producto": "counting NADPH is counting product",
    "lámpara": "lamp",
    "luz de 340 nm": "340 nm light",
    "cubeta": "cuvette",
    "sale menos luz": "less light comes out",
    "tiempo": "time",
    "absorbancia a 340 nm": "absorbance at 340 nm",
    "pendiente ∝ v₀": "slope ∝ v₀",
    "La enzima es un guía que conoce el paso más bajo": "The enzyme is a guide who knows the lowest pass",
    "Mismo punto de partida, mismo destino: solo cambia la altura del camino":
        "Same start, same destination: only the height of the path changes",
    "sin enzima": "without enzyme",
    "con enzima": "with enzyme",
    "paso alto (sin enzima):": "high pass (no enzyme):",
    "casi nadie lo cruza": "almost nobody gets over",
    "paso bajo (con enzima):": "low pass (with enzyme):",
    "el camino del guía": "the guide’s route",
    "El mapa del curso: de los átomos a la curva de velocidad": "The course map: from atoms to the rate curve",
    "Cada flecha es una idea que conecta una sección con la siguiente": "Each arrow is an idea linking one section to the next",
    "Estructura": "Structure",
    "3FGU: reactivos": "3FGU: reactants",
    "alineados": "lined up",
    "Dinámica molecular": "Molecular dynamics",
    "los mantiene": "keeps them",
    "alineados (NAC)": "lined up (NAC)",
    "ve la química:": "sees the chemistry:",
    "vibraciones, conf.,": "vibrations, poses,",
    "método (± error)": "method (± error)",
    "colina → k_{cat}": "hill → k_{cat}",
    "sigmoide: sensor": "sigmoid: glucose",
    "de glucosa (n ≈ 1.7)": "sensor (n ≈ 1.7)",
    "Inhibidores": "Inhibitors",
    "y activadores: K_{i},": "and activators: K_{i},",
    "huellas en L–B": "fingerprints in L–B",
    "Temperatura y pH": "Temperature and pH",
    "modulan k vía ΔH‡, ΔS‡ y los pK_{a}": "tune k via ΔH‡, ΔS‡ and the pK_{a}s",
    "estructura": "structure",
    "dinámica": "dynamics",
    "barrera y velocidad": "barrier and rate",
    "cinética de laboratorio": "lab kinetics",
    "condiciones": "conditions",
    "De los átomos a la velocidad: la glucoquinasa, paso a paso": "From atoms to rates: glucokinase, step by step",
    "Una reacción real, cuatro miradas y los números medidos en el laboratorio":
        "One real reaction, four viewpoints and the numbers measured in the lab",
    "(la enzima)": "(the enzyme)",
    "glucosa": "glucose",
    "glucosa-6-fosfato": "glucose-6-phosphate",
    "la foto 3D (3FGU)": "the 3D snapshot (3FGU)",
    "la película de la enzima": "the enzyme’s movie",
    "Química cuántica": "Quantum chemistry",
    "QM/MM: la colina": "QM/MM: the hill",
    "Cinética": "Kinetics",
    "Hill, inhibidores": "Hill, inhibitors",
    "Qué hace la glucoquinasa: mover un fosfato": "What glucokinase does: move a phosphate",
    "El fosfato γ del ATP salta al oxígeno O6 de la glucosa; Asp205 se lleva el protón":
        "ATP’s γ-phosphate jumps to glucose’s O6 oxygen; Asp205 takes the proton",
    "adenosina": "adenosine",
    "se rompe": "breaks",
    "sujeta y calma": "holds and calms",
    "las cargas del fosfato": "the phosphate charges",
    "el fosfato γ salta": "the γ-phosphate jumps",
    "del ATP al O6": "from ATP to O6",
    "la base: se lleva": "the base: takes",
    "el protón del O6": "the O6 proton",
    "estabiliza el fosfato": "stabilizes the phosphate",
    "que viaja": "in transit",
    "Resultado: glucosa-6-fosfato + ADP. Con el fosfato pegado, la glucosa ya no puede salir de la célula.":
        "Result: glucose-6-phosphate + ADP. With the phosphate attached, glucose can no longer leave the cell.",
    "Un sensor de glucosa que decide cuánta insulina liberar": "A glucose sensor that decides how much insulin to release",
    "La glucoquinasa trabaja más cuanta más glucosa hay en la sangre": "Glucokinase works harder the more glucose there is in the blood",
    "sangre": "blood",
    "célula β del páncreas": "pancreatic β cell",
    "más glucosa, más actividad": "more glucose, more activity",
    "insulina liberada": "insulin released",
    "más glucosa → más insulina": "more glucose → more insulin",
    "Si una mutación frena a la glucoquinasa, el páncreas «ve» menos glucosa de la que hay: diabetes GCK-MODY.":
        "If a mutation slows glucokinase, the pancreas “sees” less glucose than there is: GCK-MODY diabetes.",
    "Si la acelera, libera insulina de más: hipoglucemia congénita.":
        "If it speeds it up, too much insulin is released: congenital hypoglycemia.",
    "Velocidad = cuánto producto aparece por segundo": "Rate = how much product appears per second",
    "Como contar las monedas que caen en un frasco: al principio el ritmo es constante":
        "Like counting coins dropping into a jar: at first the pace is steady",
    "0 µM de producto": "0 µM of product",
    "5 µM de producto": "5 µM of product",
    "10 µM de producto": "10 µM of product",
    "1 µM por segundo ⇒ v₀ = 1 µM/s": "1 µM per second ⇒ v₀ = 1 µM/s",
    "tiempo →": "time →",
    "producto ↑": "product ↑",
    "pendiente inicial": "initial slope",
    "después la curva se dobla:": "later the curve bends:",
    "el sustrato se agota": "the substrate runs out",
})

FIG_EN.update({
    # ------------------------------------------------------------------ fig_B: estructura
    "La glucoquinasa se cierra sobre la glucosa como una almeja": "Glucokinase closes over glucose like a clamshell",
    "Dos dominios unidos por una bisagra: abierta atrapa poco; cerrada, alinea los reactivos":
        "Two domains joined by a hinge: open, it traps little; closed, it lines up the reactants",
    "dominio pequeño": "small domain",
    "dominio grande": "large domain",
    "bisagra": "hinge",
    "Abierta: poco activa": "Open: barely active",
    "Cerrada: lista para reaccionar": "Closed: ready to react",
    "se cierra": "closes",
    "fosfatos del ATP": "ATP phosphates",
    "El truco del cristalógrafo: un ATP que no puede reaccionar": "The crystallographer’s trick: an ATP that cannot react",
    "Cambiar un solo átomo (O3B → N3B) congela el complejo justo antes de la química":
        "Changing one atom (O3B → N3B) freezes the complex just before the chemistry",
    "AMP-PNP (en el cristal)": "AMP-PNP (in the crystal)",
    "el puente N no se rompe: no reacciona": "the N bridge doesn’t break: no reaction",
    "ATP (en nuestra simulación)": "ATP (in our simulation)",
    "el puente O sí se rompe: reacciona": "the O bridge does break: it reacts",
    "a la glucosa": "to glucose",
    "Conformación de ataque cercano: cuando los reactivos se apuntan": "Near-attack conformation: when the reactants take aim",
    "Solo desde esas posturas puede ocurrir la química; la MD mide qué fracción del tiempo pasa en ellas":
        "Chemistry can only start from these poses; MD measures the fraction of time spent in them",
    "Ataque cercano (NAC)": "Near attack (NAC)",
    "el O6 apunta al fósforo y está cerca": "O6 points at the phosphorus and is close",
    "→ la reacción es posible": "→ the reaction is possible",
    "No reactiva": "Non-reactive",
    "demasiado lejos o mal orientado": "too far or badly oriented",
    "→ hay que esperar a que se acerque": "→ we must wait for it to come closer",
    "Cómo se hace cada fotograma: las leyes de Newton, una y otra vez": "How each frame is made: Newton’s laws, over and over",
    "Átomos = bolitas con masa; enlaces = resortes; además cargas que se atraen o repelen":
        "Atoms = balls with mass; bonds = springs; plus charges that attract or repel",
    "bolita = átomo (masa m)": "ball = atom (mass m)",
    "resorte = enlace": "spring = bond",
    "1. Posiciones": "1. Positions",
    "dónde está cada átomo": "where each atom is",
    "2. Fuerzas": "2. Forces",
    "resortes + cargas + choques": "springs + charges + collisions",
    "3. Aceleración": "3. Acceleration",
    "4. Mover 2 fs": "4. Move 2 fs",
    "posición nueva": "new position",
    "vueltas = 1 ns": "loops = 1 ns",
    "El cristal es una foto; la dinámica molecular es la película": "The crystal is a photo; molecular dynamics is the movie",
    "Cada fotograma avanza 2 femtosegundos; un nanosegundo son 500 000 fotogramas":
        "Each frame moves 2 femtoseconds ahead; one nanosecond is 500 000 frames",
    "3FGU: una sola pose": "3FGU: a single pose",
    "Foto (cristal)": "Photo (crystal)",
    "Película (dinámica molecular)": "Movie (molecular dynamics)",
    "La distancia P···O cambia en cada fotograma: los reactivos «vibran», pero siguen apuntándose.":
        "The P···O distance changes every frame: the reactants “jiggle” but keep aiming at each other.",
    "De la foto del cristal a un modelo que se puede simular": "From the crystal photo to a model we can simulate",
    "Cuatro arreglos antes de encender la simulación (script 01_preparar_sistema.py)":
        "Four fixes before starting the simulation (script 01_preparar_sistema.py)",
    "Añadir hidrógenos": "Add hydrogens",
    "los rayos X no ven": "X-rays cannot see",
    "los átomos de H": "the H atoms",
    "Completar bucles": "Rebuild loops",
    "3 trozos desordenados": "3 disordered pieces",
    "se modelan (PDBFixer)": "are modeled (PDBFixer)",
    "bucle añadido": "added loop",
    "cadena del cristal": "crystal chain",
    "Poner parámetros": "Assign parameters",
    "resortes y cargas:": "springs and charges:",
    "enlaces = resortes": "bonds = springs",
    "Agua e iones": "Water and ions",
    "caja TIP3P de 10 Å y": "10 Å TIP3P box and",
    "21 Na⁺ (puntos violeta)": "21 Na⁺ (violet dots)",
    "El sitio activo en el cristal (3FGU): todo listo para reaccionar": "The active site in the crystal (3FGU): all set to react",
    "Esquema plano; las distancias son las medidas en la estructura cristalina":
        "Flat sketch; distances are those measured in the crystal structure",
    "base catalítica (−)": "catalytic base (−)",
    "puente de H": "H-bond",
    "trifosfato del ATP": "ATP triphosphate",
    "(→ adenosina)": "(→ adenosine)",
    "aún sin": "not yet",
    "enlace": "bonded",
    "Mg²⁺ neutraliza": "Mg²⁺ neutralizes",
    "carga (+)": "charge (+)",
    "distancia medida": "measured distance",
    "lo que ocurrirá": "what will happen",
})

FIG_EN.update({
    # ------------------------------------------------------------------ fig_C: QM/MM
    "¿Cuánto hace el resto de la enzima?": "How much does the rest of the enzyme do?",
    "Sacamos el sitio activo de la proteína, lo ponemos en agua y volvemos a medir la colina":
        "We take the active site out of the protein, put it in water and measure the hill again",
    "energía (kcal/mol)": "energy (kcal/mol)",
    "diferencia: 2.5 kcal/mol": "difference: 2.5 kcal/mol",
    "dentro de la enzima: barrera 19.1 kcal/mol": "inside the enzyme: barrier 19.1 kcal/mol",
    "el mismo clúster en agua (COSMO): 21.6 kcal/mol": "the same cluster in water (COSMO): 21.6 kcal/mol",
    "El clúster en agua conserva…": "The cluster in water keeps…",
    "glucosa + trifosfato": "glucose + triphosphate",
    "Asp205, la base": "Asp205, the base",
    "Lys169, la carga +": "Lys169, the + charge",
    "Mg²⁺ y su agua": "Mg²⁺ and its water",
    "…pero pierde": "…but loses",
    "el campo eléctrico y el «molde»": "the electric field and the “mold”",
    "del resto de la proteína": "of the rest of the protein",
    "Por eso las dos colinas se parecen.": "That is why the two hills look alike.",
    "De la barrera al número de recambio": "From the barrier to the turnover number",
    "Una sola regla, dos escalas: cada 1.36 kcal/mol hacia la derecha, la reacción es 10 veces más lenta":
        "One rule, two scales: every 1.36 kcal/mol to the right, the reaction is 10 times slower",
    "barrera ΔG‡ (kcal/mol)": "barrier ΔG‡ (kcal/mol)",
    "k = k_{cat} por Eyring (s⁻¹, 25 °C)": "k = k_{cat} from Eyring (s⁻¹, 25 °C)",
    "experimento": "experiment",
    "QM/MM publicada (Zhang 2009)": "published QM/MM (Zhang 2009)",
    "ΔE‡ de este cuaderno": "ΔE‡ from this notebook",
    "ΔG‡ con vibraciones": "ΔG‡ with vibrations",
    "sitio activo en agua": "active site in water",
    "los cálculos QM/MM ponen 3–4 kcal/mol de más ⇒ una reacción ~10^{2}–10^{3} veces más lenta":
        "the QM/MM calculations overshoot by 3–4 kcal/mol ⇒ a reaction ~10^{2}–10^{3} times slower",
    "La prueba del punto de silla: una sola frecuencia imaginaria": "The saddle-point test: exactly one imaginary frequency",
    "Cada frecuencia es un «resorte» del sistema; en la silla hay un resorte al revés":
        "Each frequency is a “spring” of the system; at the saddle one spring is upside down",
    "En un valle (R o P)": "In a valley (R or P)",
    "oscila": "oscillates",
    "todas las direcciones suben": "every direction goes uphill",
    "todas las frecuencias son reales": "all frequencies are real",
    "Silla, a lo ancho del paso": "Saddle, across the pass",
    "subes hacia las montañas": "you climb toward the peaks",
    "frecuencia real (vibra)": "real frequency (vibrates)",
    "Silla, a lo largo del camino": "Saddle, along the path",
    "bajas hacia R o hacia P": "you slide down to R or to P",
    "frecuencia imaginaria: −149 cm⁻¹": "imaginary frequency: −149 cm⁻¹",
    "Animar el modo imaginario muestra la química: el fósforo va y viene entre O3β y O6.":
        "Animating the imaginary mode shows the chemistry: the phosphorus shuttles between O3β and O6.",
    "El estado de transición es un paso de montaña": "The transition state is a mountain pass",
    "Mapa de curvas de nivel: dos valles (azul oscuro) separados por un collado":
        "Contour map: two valleys (dark blue) separated by a col",
    "reactivo": "reactant",
    "producto": "product",
    "punto de silla": "saddle point",
    "(imagen trepadora del NEB)": "(NEB climbing image)",
    "Las cuentas unidas por muelles (el NEB) se asientan sobre el camino de mínima energía entre los dos valles.":
        "The beads joined by springs (the NEB) settle onto the minimum-energy path between the two valleys.",
    "Cómo se encuentra": "How it is found",
    "NEB con imagen trepadora": "NEB with a climbing image",
    "una cadena de geometrías unidas por": "a chain of geometries joined by",
    "muelles se relaja sobre el camino;": "springs relaxes onto the path;",
    "la cuenta central trepa a la cima": "the central bead climbs to the top",
    "Método del dímero": "Dimer method",
    "dos puntos muy juntos «tantean» la": "two very close points “feel” the",
    "curvatura y refinan la cima hasta": "curvature and refine the summit until",
    "que la fuerza es cero": "the force is zero",
    "Frecuencias": "Frequencies",
    "en una silla hay exactamente una": "a saddle has exactly one",
    "frecuencia imaginaria: la dirección": "imaginary frequency: the direction",
    "en la que la geometría «cae»": "in which the geometry “falls”",
    "QM/MM: enfocar el balón y dejar el estadio de fondo": "QM/MM: focus on the ball, leave the stadium as background",
    "La mecánica cuántica es cara: solo se usa donde ocurre la química":
        "Quantum mechanics is expensive: it is used only where the chemistry happens",
    "Fotografía de un partido": "Photographing a match",
    "enfocas el balón; las gradas quedan de fondo": "you focus on the ball; the stands stay in the background",
    "La enzima en QM/MM": "The enzyme in QM/MM",
    "78 átomos cuánticos; ~57 000 clásicos": "78 quantum atoms; ~57 000 classical",
    "región QM": "QM region",
    "(mecánica cuántica)": "(quantum mechanics)",
    "región MM (campo de fuerza)": "MM region (force field)",
    "Dos regiones que se ven: electricidad y «codos»": "Two regions that see each other: electricity and “elbows”",
    "La región QM siente las cargas de la enzima y no puede atravesar sus átomos":
        "The QM region feels the enzyme’s charges and cannot pass through its atoms",
    "78 átomos, carga −2": "78 atoms, charge −2",
    "átomo de enlace: un H tapa el": "link atom: an H caps the",
    "enlace cortado en la frontera": "bond cut at the boundary",
    "región MM: ~2300 cargas fijas": "MM region: ~2300 fixed charges",
    "1 · Electrostática (embedding)": "1 · Electrostatics (embedding)",
    "las cargas MM crean un potencial eléctrico que": "the MM charges create an electric potential that",
    "entra en el cálculo cuántico: los electrones": "enters the quantum calculation: the QM",
    "QM se desplazan hacia las cargas +": "electrons shift toward the + charges",
    "atrae": "attracts",
    "2 · Lennard-Jones (los «codos»)": "2 · Lennard-Jones (the “elbows”)",
    "repulsión de corto alcance entre átomos QM y MM;": "short-range repulsion between QM and MM atoms;",
    "sin ella la electrostática, que solo atrae,": "without it, electrostatics, which only attracts,",
    "«hundiría» la región QM en la proteína": "would “sink” the QM region into the protein",
    "repele de cerca": "repels up close",
    "E_{PM7}[QM en la enzima]": "E_{PM7}[QM in the enzyme]",
    "De ΔE‡ a ΔG‡: tres preguntas de un buen científico": "From ΔE‡ to ΔG‡: three questions a good scientist asks",
    "Cada pregunta es un cálculo extra; solo la primera cambia el número, las otras dicen cuánto fiarse":
        "Each question is an extra calculation; only the first changes the number, the others say how much to trust it",
    "¿Y las vibraciones?": "What about vibrations?",
    "los átomos nunca están quietos:": "atoms are never still:",
    "energía de punto cero y entropía": "zero-point energy and entropy",
    "¿Y otra postura de la enzima?": "Another enzyme pose?",
    "repetir en 4 instantáneas de": "repeat on 4 snapshots from",
    "la MD (250–1000 ps)": "the MD (250–1000 ps)",
    "¿Y si el método se equivoca?": "What if the method is wrong?",
    "recalcular con PM6-D3H4 en": "recompute with PM6-D3H4 on",
    "las mismas geometrías": "the same geometries",
    "Solo la pregunta 1 corrige la barrera (kcal/mol, 25 °C):": "Only question 1 corrects the barrier (kcal/mol, 25 °C):",
    "El resorte que se rompe pierde su vibración (ΔZPE < 0 baja la barrera); el estado de transición es":
        "The breaking spring loses its vibration (ΔZPE < 0 lowers the barrier); the transition state is",
    "más rígido que el reactivo (ΔS‡ < 0), así que −TΔS‡ la sube. Casi se compensan.":
        "stiffer than the reactant (ΔS‡ < 0), so −TΔS‡ raises it. The two almost cancel.",
    "ξ: un solo número que dice «dónde está el fosfato»": "ξ: a single number that says “where the phosphate is”",
    "ξ = d(Pγ–O3β) − d(Pγ–O6): negativa en el reactivo, ≈ 0 en la cima, positiva en el producto":
        "ξ = d(Pγ–O3β) − d(Pγ–O6): negative in the reactant, ≈ 0 at the summit, positive in the product",
    "el fosfato sigue en el ATP": "the phosphate is still on ATP",
    "el fosfato ya está en la glucosa": "the phosphate is now on glucose",
    "Los enlaces sólidos están formados; los discontinuos, a medio formar o a medio romper.":
        "Solid bonds are formed; dashed ones are half formed or half broken.",
})

FIG_EN.update({
    # ------------------------------------------------------------------ fig_D: cinética
    "La enzima es una caja de supermercado": "The enzyme is a supermarket checkout",
    "Con pocos clientes la caja espera; con una cola larga trabaja a tope y ya no puede ir más rápido":
        "With few customers the cashier waits; with a long line it works flat out and can go no faster",
    "Pocos clientes": "Few customers",
    "caja": "checkout",
    "libre": "idle",
    "tiempo ocupada": "time busy",
    "la caja espera casi siempre:": "the cashier waits most of the time:",
    "cada cliente nuevo cuenta": "every new customer counts",
    "Algunos clientes": "Some customers",
    "ocupada la mitad del tiempo:": "busy half of the time:",
    "Cola larga": "Long line",
    "siempre ocupada: v_{0} → V_{max};": "always busy: v_{0} → V_{max};",
    "da igual que lleguen más": "more arrivals make no difference",
    "[S]  (clientes que llegan)": "[S]  (customers arriving)",
    "meseta: saturación": "plateau: saturation",
    "tramo casi recto (al principio)": "almost straight stretch (at first)",
    "Cooperatividad cinética: una enzima con memoria": "Kinetic cooperativity: an enzyme with a memory",
    "Un solo sitio activo, dos formas que se interconvierten tan despacio como la propia catálisis":
        "One active site, two forms that interconvert as slowly as catalysis itself",
    "forma abierta": "open form",
    "poco activa (lenta)": "barely active (slow)",
    "forma cerrada": "closed form",
    "activa (rápida)": "active (fast)",
    "se cierra al unir glucosa": "closes when glucose binds",
    "se relaja despacio si no llega otra glucosa": "relaxes slowly if no new glucose arrives",
    "poca glucosa": "little glucose",
    "entre una glucosa y la siguiente se relaja: casi siempre lenta": "it relaxes between one glucose and the next: mostly slow",
    "mucha glucosa": "lots of glucose",
    "la siguiente llega antes de relajarse: sigue rápida": "the next one arrives before it relaxes: it stays fast",
    "forma rápida": "fast form",
    "forma lenta": "slow form",
    "llega una glucosa": "a glucose arrives",
    "Tres maneras de frenar la caja": "Three ways to slow down the checkout",
    "Cada tipo de inhibidor deja una huella distinta en V_{max}, en K_{M} y en el gráfico de Lineweaver–Burk":
        "Each inhibitor type leaves its own fingerprint on V_{max}, on K_{M} and on the Lineweaver–Burk plot",
    "Competitivo": "Competitive",
    "se pone en la cola sin comprar": "joins the line without buying",
    "ocupa el turno (se une a E)": "takes a turn (binds to E)",
    "V_{max} aparente": "apparent V_{max}",
    "=  igual": "=  same",
    "K_{M} aparente": "apparent K_{M}",
    "↑  sube": "↑  up",
    "se cruzan en el eje vertical": "cross on the vertical axis",
    "Acompetitivo": "Uncompetitive",
    "traba la caja con un cliente": "jams the till with a customer",
    "atrapa al complejo ES": "traps the ES complex",
    "↓  baja": "↓  down",
    "rectas paralelas": "parallel lines",
    "No competitivo": "Noncompetitive",
    "apaga la luz de la caja": "switches off the till light",
    "se une a E y a ES por igual": "binds E and ES equally",
    "se cruzan en el eje horizontal": "cross on the horizontal axis",
    "sin inhibidor": "no inhibitor",
    "con inhibidor": "with inhibitor",
    "El mecanismo detrás de la hipérbola": "The mechanism behind the hyperbola",
    "Tres pasos elementales, tres constantes de velocidad": "Three elementary steps, three rate constants",
    "enzima libre": "free enzyme",
    "sustrato": "substrate",
    "complejo enzima-sustrato": "enzyme–substrate complex",
    "vuelve libre": "free again",
    "el cliente llega a la caja": "the customer reaches the till",
    "(choque productivo)": "(productive encounter)",
    "se va sin comprar": "leaves without buying",
    "(el sustrato se suelta)": "(substrate lets go)",
    "paga y sale con la compra": "pays and leaves with the goods",
    "(cruza la barrera: química)": "(crosses the barrier: chemistry)",
    "En la analogía del cajero:": "In the cashier analogy:",
    "Michaelis–Menten en palabras: velocidad = máxima × fracción ocupada":
        "Michaelis–Menten in words: rate = maximum × fraction occupied",
    "velocidad máxima": "maximum rate",
    "toda la enzima trabajando:": "all the enzyme working:",
    "fracción de enzima ocupada": "fraction of enzyme occupied",
    "de 0 (caja vacía) a 1": "from 0 (empty till) to 1",
    "(caja siempre ocupada)": "(till always busy)",
    "La fracción ocupada": "The fraction occupied",
    "K_{M} = [S] a media ocupación": "K_{M} = [S] at half occupancy",
    "La campana de pH: dos grupos, dos condiciones": "The pH bell: two groups, two conditions",
    "Asp205 debe estar sin protón (para aceptarlo) y Lys169 con protón (para sujetar el fosfato)":
        "Asp205 must lack a proton (to accept one) and Lys169 must carry one (to hold the phosphate)",
    "actividad": "activity",
    "óptimo = (pK₁ + pK₂) / 2": "optimum = (pK₁ + pK₂) / 2",
    "glucoquinasa: pH 8.5–8.7": "glucokinase: pH 8.5–8.7",
    "pH bajo": "low pH",
    "la base ya tiene protón: no acepta otro": "the base is already protonated",
    "pH óptimo": "optimal pH",
    "los dos grupos listos": "both groups ready",
    "pH alto": "high pH",
    "la lisina perdió su carga positiva": "the lysine lost its positive charge",
    "Regulador de luz frente a interruptor con umbral": "Dimmer versus threshold switch",
    "Franja sombreada: cuánto hay que multiplicar [S] para pasar del 10 % al 90 % (eje x logarítmico)":
        "Shaded band: how much [S] must be multiplied to go from 10 % to 90 % (log x axis)",
    "Regulador de luz": "Dimmer",
    "hipérbola, n = 1 (Michaelis–Menten)": "hyperbola, n = 1 (Michaelis–Menten)",
    "Interruptor con umbral": "Threshold switch",
    "sigmoide, n = 1.7 (glucoquinasa)": "sigmoid, n = 1.7 (glucokinase)",
    "Calentar = sacudidas más fuertes": "Heating = stronger thermal kicks",
    "Cuántas moléculas tienen cada energía; solo la cola que supera la barrera reacciona":
        "How many molecules have each energy; only the tail above the barrier reacts",
    "energía de la molécula →": "molecular energy →",
    "nº de": "no. of",
    "moléculas": "molecules",
    "barrera": "barrier",
    "estas sí reaccionan": "these do react",
    "En números": "In numbers",
    "Con E_{a} = 12 kcal/mol,": "With E_{a} = 12 kcal/mol,",
    "de 25 a 37 °C la cola": "from 25 to 37 °C the tail",
    "crece ~2.2 veces:": "grows ~2.2 times:",
    "k se multiplica por 2.2.": "k is multiplied by 2.2.",
    "Dibujo esquemático: la": "Schematic drawing: the",
    "diferencia entre las curvas": "difference between the curves",
    "está exagerada para verla.": "is exaggerated to make it visible.",
})

# textos que no cambian con el idioma (números, fórmulas, símbolos, siglas, nombres propios)
_NEUTROS = [
    "ΔG^{‡}", "k", "=", "κ · k_{B}T / h", "×", "exp(−ΔG^{‡} / RT)", "×1", "÷10", "÷100", "÷1000",
    "G6P", "G6PDH", "NADP⁺", "NADPH", "1 G6P ⇒ 1 NADPH:", "detector", "G6P + ADP",
    "§3–4", "§5", "QM/MM", "R → TS → P", "§7–9", "§10–11", "ΔE‡ → ΔG‡", "§6, §12", "Eyring", "1.36 kcal/mol = ×10",
    "§13", "Michaelis–Menten", "K_{M}, V_{max}, k_{cat}/K_{M}", "§14", "Hill", "§15", "§16",
    "+", "P", "ATP", "ADP", "§6–12", "§13–16", "Michaelis–Menten,",
    "α", "β", "γ", "Mg²⁺", "O6", "H", "Asp205 (–)", "Lys169 (+)",
    "t = 0 s", "t = 5 s", "t = 10 s", "= v_{0}",
    "Pβ", "Pγ", "N", "O", "N → O", "d < 3.5 Å", "d > 3.5 Å",
    "−", "F", "a = F / m", "×500 000", "t = 0 fs", "t = 2 fs", "t = 4 fs", "t = 6 fs", "…",
    "1", "+ H", "2", "3", "ff14SB, GAFF2, Li–Merz", "δ+", "δ−", "4",
    "C6", "Asp205", "2.5 Å", "Pα", "O3β", "2.7 Å", "Mg", "N⁺", "Lys169",
    "−10", "0", "10", "20", "R",
    "13", "14", "15", "16", "17", "18", "19", "21", "22", "23",
    "10^{3}", "10^{2}", "10^{1}", "10^{0}", "10^{−1}", "10^{−2}", "10^{−3}", "10^{−4}",
    "k_{cat} ≈ 66 s⁻¹ → ΔG‡ ≈ 15.0", "18.3", "19.1", "19.75", "21.6",
    "E  =", "E_{LJ}", "PM7", "19.1 kcal/mol", "PM6-D3H4", "4.5 kcal/mol",
    "ΔE‡ 19.13", "ΔZPE −0.24", "ΔH_{vib} −0.43", "−TΔS‡ +1.29", "ΔG‡ 19.75",
    "1.67 Å", "3.23 Å", "ξ = 1.67 − 3.23 = −1.56 Å", "2.22 Å", "2.10 Å", "ξ = 2.22 − 2.10 = +0.12 Å",
    "3.43 Å", "1.68 Å", "ξ = 3.43 − 1.68 = +1.75 Å", "−2", "−1", "+1", "+2", "ξ (Å)",
    "[S] ≪ K_{M}", "12 %", "[S] = K_{M}", "50 %", "v_{0} = V_{max} / 2", "[S] ≫ K_{M}", "88 %",
    "v₀", "V_{max}", "V_{max}/2", "K_{M}",
    "k_{ex} ≈ 5–100 s^{−1}  vs  k_{cat} ≈ 60 s^{−1}",
    "I", "1/[S]", "1/v₀",
    "E", "S", "k_{1}", "k_{−1}", "ES", "k_{2} = k_{cat}", "k_{2}",
    "v_{0}", "k_{cat} · [E]_{0}", "[S] / (K_{M} + [S])", "[S] = K_{M}/10", "≈ 9 %", "[S] = 10 K_{M}", "≈ 91 %",
    "pH →", "pK_{1}", "pK_{2}", "COOH", "✗", "NH₃⁺", "✓", "COO⁻", "NH₂",
    "0.1", "[S] / S₀.₅", "10 %", "90 %", "[S] × 81", "[S] × 13",
    "E_{a}", "25 °C", "37 °C",
]
FIG_EN.update({s: s for s in _NEUTROS if s not in FIG_EN})

# textos que ya llegan en mayúsculas (pastillas y títulos de las viñetas R/TS/P): su versión en inglés, también en mayúsculas
FIG_EN.update({k.upper(): FIG_EN[k].upper() for k in (
    "Analogía", "La ecuación, término a término", "La ecuación, en palabras", "Cómo se mide", "Resumen",
    "El curso en una imagen", "La reacción", "Por qué importa", "Para pensar", "Modelo", "Datos reales",
    "reactivo", "producto", "estado de transición")})
# y la versión ya traducida en mayúsculas (la pastilla traduce y luego escribe en mayúsculas)
FIG_EN.update({v: v for v in list(FIG_EN.values()) if v.isupper() and v not in FIG_EN})
